apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: gcr.io/gcp-project-368920/gcproject
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: clusterip-service 

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: helloworld
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer